<?php
/**
 * ExternalConnection
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\weclapp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\weclapp\Model;

use \ArrayAccess;
use \kruegge82\weclapp\ObjectSerializer;

/**
 * ExternalConnection Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\weclapp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ExternalConnection implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'externalConnection';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'version' => 'string',
        'connection_type' => 'string',
        'created_date' => 'int',
        'last_modified_date' => 'int',
        'name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'version' => null,
        'connection_type' => null,
        'created_date' => 'timestamp',
        'last_modified_date' => 'timestamp',
        'name' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'version' => false,
        'connection_type' => false,
        'created_date' => false,
        'last_modified_date' => false,
        'name' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'version' => 'version',
        'connection_type' => 'connectionType',
        'created_date' => 'createdDate',
        'last_modified_date' => 'lastModifiedDate',
        'name' => 'name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'version' => 'setVersion',
        'connection_type' => 'setConnectionType',
        'created_date' => 'setCreatedDate',
        'last_modified_date' => 'setLastModifiedDate',
        'name' => 'setName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'version' => 'getVersion',
        'connection_type' => 'getConnectionType',
        'created_date' => 'getCreatedDate',
        'last_modified_date' => 'getLastModifiedDate',
        'name' => 'getName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CONNECTION_TYPE_AMAZON = 'AMAZON';
    public const CONNECTION_TYPE_BREVO = 'BREVO';
    public const CONNECTION_TYPE_CLEVERREACH = 'CLEVERREACH';
    public const CONNECTION_TYPE_DATEV_CONNECT_ONLINE_PROD = 'DATEV_CONNECT_ONLINE_PROD';
    public const CONNECTION_TYPE_DATEV_CONNECT_ONLINE_STAGING = 'DATEV_CONNECT_ONLINE_STAGING';
    public const CONNECTION_TYPE_DHL = 'DHL';
    public const CONNECTION_TYPE_EBAY = 'EBAY';
    public const CONNECTION_TYPE_FINTEC_SYSTEMS = 'FINTEC_SYSTEMS';
    public const CONNECTION_TYPE_GOOGLEV3 = 'GOOGLEV3';
    public const CONNECTION_TYPE_ITSCOPE = 'ITSCOPE';
    public const CONNECTION_TYPE_JIRA = 'JIRA';
    public const CONNECTION_TYPE_KAUFLAND = 'KAUFLAND';
    public const CONNECTION_TYPE_MAGENTO = 'MAGENTO';
    public const CONNECTION_TYPE_MAGENTO2 = 'MAGENTO2';
    public const CONNECTION_TYPE_MAILCHIMP = 'MAILCHIMP';
    public const CONNECTION_TYPE_MAPBOX = 'MAPBOX';
    public const CONNECTION_TYPE_MOLLIE_PROD = 'MOLLIE_PROD';
    public const CONNECTION_TYPE_MOLLIE_STAGING = 'MOLLIE_STAGING';
    public const CONNECTION_TYPE_NAMIRIAL_2_C_SOLUTION = 'NAMIRIAL_2C_SOLUTION';
    public const CONNECTION_TYPE_OTTO = 'OTTO';
    public const CONNECTION_TYPE_PRESTA = 'PRESTA';
    public const CONNECTION_TYPE_SENDCLOUD = 'SENDCLOUD';
    public const CONNECTION_TYPE_SHIPCLOUD = 'SHIPCLOUD';
    public const CONNECTION_TYPE_SHOPIFY = 'SHOPIFY';
    public const CONNECTION_TYPE_SHOPWARE = 'SHOPWARE';
    public const CONNECTION_TYPE_SHOPWARE6 = 'SHOPWARE6';
    public const CONNECTION_TYPE_STRIPE_PROD = 'STRIPE_PROD';
    public const CONNECTION_TYPE_STRIPE_STAGING = 'STRIPE_STAGING';
    public const CONNECTION_TYPE_SYNAXON = 'SYNAXON';
    public const CONNECTION_TYPE_TEAMVIEWER = 'TEAMVIEWER';
    public const CONNECTION_TYPE_TINK = 'TINK';
    public const CONNECTION_TYPE_VERSACOMMERCE = 'VERSACOMMERCE';
    public const CONNECTION_TYPE_WECLAPP2_WECLAPP = 'WECLAPP2WECLAPP';
    public const CONNECTION_TYPE_WOOCOMMERCE = 'WOOCOMMERCE';
    public const CONNECTION_TYPE_XTCOMMERCE = 'XTCOMMERCE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getConnectionTypeAllowableValues()
    {
        return [
            self::CONNECTION_TYPE_AMAZON,
            self::CONNECTION_TYPE_BREVO,
            self::CONNECTION_TYPE_CLEVERREACH,
            self::CONNECTION_TYPE_DATEV_CONNECT_ONLINE_PROD,
            self::CONNECTION_TYPE_DATEV_CONNECT_ONLINE_STAGING,
            self::CONNECTION_TYPE_DHL,
            self::CONNECTION_TYPE_EBAY,
            self::CONNECTION_TYPE_FINTEC_SYSTEMS,
            self::CONNECTION_TYPE_GOOGLEV3,
            self::CONNECTION_TYPE_ITSCOPE,
            self::CONNECTION_TYPE_JIRA,
            self::CONNECTION_TYPE_KAUFLAND,
            self::CONNECTION_TYPE_MAGENTO,
            self::CONNECTION_TYPE_MAGENTO2,
            self::CONNECTION_TYPE_MAILCHIMP,
            self::CONNECTION_TYPE_MAPBOX,
            self::CONNECTION_TYPE_MOLLIE_PROD,
            self::CONNECTION_TYPE_MOLLIE_STAGING,
            self::CONNECTION_TYPE_NAMIRIAL_2_C_SOLUTION,
            self::CONNECTION_TYPE_OTTO,
            self::CONNECTION_TYPE_PRESTA,
            self::CONNECTION_TYPE_SENDCLOUD,
            self::CONNECTION_TYPE_SHIPCLOUD,
            self::CONNECTION_TYPE_SHOPIFY,
            self::CONNECTION_TYPE_SHOPWARE,
            self::CONNECTION_TYPE_SHOPWARE6,
            self::CONNECTION_TYPE_STRIPE_PROD,
            self::CONNECTION_TYPE_STRIPE_STAGING,
            self::CONNECTION_TYPE_SYNAXON,
            self::CONNECTION_TYPE_TEAMVIEWER,
            self::CONNECTION_TYPE_TINK,
            self::CONNECTION_TYPE_VERSACOMMERCE,
            self::CONNECTION_TYPE_WECLAPP2_WECLAPP,
            self::CONNECTION_TYPE_WOOCOMMERCE,
            self::CONNECTION_TYPE_XTCOMMERCE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('connection_type', $data ?? [], null);
        $this->setIfExists('created_date', $data ?? [], null);
        $this->setIfExists('last_modified_date', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['connection_type'] === null) {
            $invalidProperties[] = "'connection_type' can't be null";
        }
        $allowedValues = $this->getConnectionTypeAllowableValues();
        if (!is_null($this->container['connection_type']) && !in_array($this->container['connection_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'connection_type', must be one of '%s'",
                $this->container['connection_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string|null $version version
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets connection_type
     *
     * @return string
     */
    public function getConnectionType()
    {
        return $this->container['connection_type'];
    }

    /**
     * Sets connection_type
     *
     * @param string $connection_type connection_type
     *
     * @return self
     */
    public function setConnectionType($connection_type)
    {
        if (is_null($connection_type)) {
            throw new \InvalidArgumentException('non-nullable connection_type cannot be null');
        }
        $allowedValues = $this->getConnectionTypeAllowableValues();
        if (!in_array($connection_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'connection_type', must be one of '%s'",
                    $connection_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['connection_type'] = $connection_type;

        return $this;
    }

    /**
     * Gets created_date
     *
     * @return int|null
     */
    public function getCreatedDate()
    {
        return $this->container['created_date'];
    }

    /**
     * Sets created_date
     *
     * @param int|null $created_date created_date
     *
     * @return self
     */
    public function setCreatedDate($created_date)
    {
        if (is_null($created_date)) {
            throw new \InvalidArgumentException('non-nullable created_date cannot be null');
        }
        $this->container['created_date'] = $created_date;

        return $this;
    }

    /**
     * Gets last_modified_date
     *
     * @return int|null
     */
    public function getLastModifiedDate()
    {
        return $this->container['last_modified_date'];
    }

    /**
     * Sets last_modified_date
     *
     * @param int|null $last_modified_date last_modified_date
     *
     * @return self
     */
    public function setLastModifiedDate($last_modified_date)
    {
        if (is_null($last_modified_date)) {
            throw new \InvalidArgumentException('non-nullable last_modified_date cannot be null');
        }
        $this->container['last_modified_date'] = $last_modified_date;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


