<?php
/**
 * ShipmentStatusType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\weclapp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * weclapp API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\weclapp\Model;
use \kruegge82\weclapp\ObjectSerializer;

/**
 * ShipmentStatusType Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\weclapp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShipmentStatusType
{
    /**
     * Possible values of this enum
     */
    public const CANCELLED = 'CANCELLED';

    public const DELIVERED = 'DELIVERED';

    public const DELIVERY_NOTE_PRINTED = 'DELIVERY_NOTE_PRINTED';

    public const INCOMING_CANCELLED = 'INCOMING_CANCELLED';

    public const INCOMING_MOVED_INTO_STORE = 'INCOMING_MOVED_INTO_STORE';

    public const INCOMING_SHIPPED = 'INCOMING_SHIPPED';

    public const IN_ROUTE = 'IN_ROUTE';

    public const _NEW = 'NEW';

    public const SHIPPED = 'SHIPPED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CANCELLED,
            self::DELIVERED,
            self::DELIVERY_NOTE_PRINTED,
            self::INCOMING_CANCELLED,
            self::INCOMING_MOVED_INTO_STORE,
            self::INCOMING_SHIPPED,
            self::IN_ROUTE,
            self::_NEW,
            self::SHIPPED
        ];
    }
}


