<?php
/**
 * SupplierOrderType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\weclapp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * weclapp API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\weclapp\Model;
use \kruegge82\weclapp\ObjectSerializer;

/**
 * SupplierOrderType Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\weclapp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SupplierOrderType
{
    /**
     * Possible values of this enum
     */
    public const DROPSHIPPING = 'DROPSHIPPING';

    public const NORMAL = 'NORMAL';

    public const SALES_ORDER = 'SALES_ORDER';

    public const SALES_ORDER_COMMISSION = 'SALES_ORDER_COMMISSION';

    public const TRIANGULAR = 'TRIANGULAR';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DROPSHIPPING,
            self::NORMAL,
            self::SALES_ORDER,
            self::SALES_ORDER_COMMISSION,
            self::TRIANGULAR
        ];
    }
}


