<?php
/**
 * UserRoleApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\weclapp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace kruegge82\weclapp\Test\Api;

use \kruegge82\weclapp\Configuration;
use \kruegge82\weclapp\ApiException;
use \kruegge82\weclapp\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserRoleApiTest Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\weclapp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserRoleApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for userRoleCountGet
     *
     * .
     *
     */
    public function testUserRoleCountGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRoleDisableUserRolesDuringTrialPost
     *
     * .
     *
     */
    public function testUserRoleDisableUserRolesDuringTrialPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRoleEnableUserRolesDuringTrialPost
     *
     * .
     *
     */
    public function testUserRoleEnableUserRolesDuringTrialPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRoleGet
     *
     * .
     *
     */
    public function testUserRoleGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRoleIdIdDelete
     *
     * .
     *
     */
    public function testUserRoleIdIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRoleIdIdGet
     *
     * .
     *
     */
    public function testUserRoleIdIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRoleIdIdPut
     *
     * .
     *
     */
    public function testUserRoleIdIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRolePost
     *
     * .
     *
     */
    public function testUserRolePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
